name: vaults_repository
description: none
publish_to: 'none'
version: 1.0.0
environment:
  sdk: '>=3.2.0 <4.0.0'
dependencies:
  flutter:
    sdk: flutter
  stashed_api:
    path: ../stashed_api
  settings_api:
    path: ../settings_api
  rxdart: ^0.27.7
  equatable: ^2.0.5
  collection: ^1.18.0
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1
flutter:
