name: stashed_api
description: none
publish_to: 'none'
version: 1.0.0
environment:
  sdk: '>=3.2.0 <4.0.0'
dependencies:
  flutter:
    sdk: flutter
  json_annotation: ^4.8.1
  dio: ^5.3.3
  logging: ^1.2.0
  rfc_6902: ^0.1.0
  equatable: ^2.0.5
  signalr_netcore: ^1.3.6
  rxdart: ^0.27.7
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1
  build_runner: ^2.4.6
  json_serializable: ^6.7.1
  build_verify: ^3.1.0
flutter:
