targets:
  $default:
    builders:
      source_gen:combining_builder:
        options:
          build_extensions:
            '^lib/src/{{dir}}/{{file}}.dart': 'lib/src/_generated/{{dir}}/{{file}}.g.dart'