name: beeapps_api
description: none
publish_to: 'none'
version: 1.0.0
environment:
  sdk: '>=3.2.0 <4.0.0'
dependencies:
  flutter:
    sdk: flutter
  path: ^1.8.3
  dio: ^5.3.3
  equatable: ^2.0.5
  json_annotation: ^4.8.1
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1
  build_runner: ^2.4.6
  json_serializable: ^6.7.1
  build_verify: ^3.1.0
flutter: