name: auth_repository
description: none
publish_to: 'none'
version: 1.0.0
environment:
  sdk: '>=3.2.0 <4.0.0'
dependencies:
  beeapps_api:
    path: ../beeapps_api
  flutter:
    sdk: flutter
  flutter_secure_storage: ^9.0.0
  collection: ^1.18.0
  rxdart: ^0.27.7
  equatable: ^2.0.5
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1
flutter:
