name: stashed
description: none
publish_to: 'none'
version: 1.0.0
environment:
  sdk: '>=3.2.0 <4.0.0'
dependencies:
  flutter:
    sdk: flutter
  beeapps_api:
    path: packages/beeapps_api
  auth_repository:
    path: packages/auth_repository
  servers_repository:
    path: packages/servers_repository
  vaults_repository:
    path: packages/vaults_repository
  tasks_repository:
    path: packages/tasks_repository
  media_repository:
    path: packages/media_repository
  queries_repository:
    path: packages/queries_repository
  stashed_api:
    path: packages/stashed_api
  settings_api:
    path: packages/settings_api
  cache_api:
    path: packages/cache_api
  equatable: ^2.0.5
  flutter_secure_storage: ^9.0.0
  bloc: ^8.1.2
  flutter_bloc: ^8.1.3
  go_router: ^13.1.0
  rxdart: ^0.27.7
  intl: ^0.18.1
  flutter_localizations:
    sdk: flutter
  dio: ^5.3.3
  logging: ^1.2.0
  formz: ^0.6.1
  path: ^1.8.3
  file_selector: ^1.0.1
  mime: ^1.0.4
  collection: ^1.18.0
  flutter_dotenv: ^5.1.0
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1
  test: ^1.24.3
  bloc_test: ^9.1.5
  mocktail: ^1.0.1
flutter:
  uses-material-design: true
  generate: true
  fonts:
    - family: NotoSans
      fonts:
        - asset: assets/fonts/NotoSans-Regular.ttf
          weight: 400
        - asset: assets/fonts/NotoSans-Medium.ttf
          weight: 500
        - asset: assets/fonts/NotoSans-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/NotoSans-Bold.ttf
          weight: 700
  assets:
    - assets/.env